Use jfbsextr in afb-fbgen script

diff --git a/flatbuffers/afb-fbgen b/flatbuffers/afb-fbgen
--- a/flatbuffers/afb-fbgen
+++ b/flatbuffers/afb-fbgen
@@ -1,8 +1,7 @@
 #!/bin/bash
 
 # dependances :
-# jq mustash flatcc
-# jq remplacé par un binaire ?
+# mustash flatcc
 
 # template will be stored in :
 # prefix/afb-idl/afb-flatbuffers/templates
@@ -21,6 +20,7 @@ PGNAME=$(corename $0)
 PGDIR=$(dirname $0)
 TEMPDIR="/tmp/$PGNAME.$$"
 : ${TEMPLATE_PATH:=$PWD}
+DATE=$(date)
 
 usage() {
 	echo "Usage :"
@@ -66,7 +66,8 @@ find_template() {
 
 header() {
 	echo "/*"
-	echo " * generated by $1 based on $2 as schema and $3 as template"
+	echo " * Generated by $1 based on $2 as schema and $3 as template"
+	echo " * Date ${DATE}"
 	echo " */"
 	echo " "
 }
@@ -82,12 +83,14 @@ generate() {
 }
 
 fbgen() {
+	local what="$1" out="$2" jspec="$3"
+
 	# determine what to generate
-	case "$1" in
-		cvt) ext=cvt; ixt=types;; # generate a convreter
+	case "$what" in
+		cvt) ext=cvt; ixt=types;; # generate a converter
 		cli) ext=cli; ixt=apis;;  # generate a client
 		api) ext=api; ixt=apis;;  # generate an api
-		*) err "invalid call"     # otherwise return an error
+		*) err "invalid call";;   # otherwise return an error
 	esac
 	
 	# Parse the output file name <ofile>-fb${ext}.<wg>
@@ -95,8 +98,8 @@ fbgen() {
 	# $ofile = "sample"
 	# $wg = "c"
 	# NB: by default <wg> is "c"
-	[ -z "$2" ] && err "no arg"
-	ofile="$2"
+	[ -z "$out" ] && err "no arg"
+	ofile="$out"
 	wg="${ofile##*.}"
 	wg="${wg:-c}"
 	ofile="${ofile%.*}"
@@ -104,7 +107,7 @@ fbgen() {
 
 	# If an input file is given in second parametter use it,
 	# otherway checkout for a file based on output name suffix
-	inspec="${3:-${ofile}-rpc-types.json}"
+	inspec="${jspec:-${ofile}-rpc-types.json}"
 
 	# Return error if not found
 	[ -f "$inspec" ] || err "spec $inspec not found"
@@ -200,18 +203,23 @@ echo "out prefix      : $out_prefix"
 # check dependencies
 trap "rm -r '$TEMPDIR'" EXIT
 [ ! -e "$TEMPDIR" ] && mkdir -p "$TEMPDIR"
-for d in "$PGDIR" "$PGDIR/../libexec" "$PGDIR/libexec"; do
-	f="$d/bfbs2json"
-	[ -x "$f" ] && { BFBS2JSON="$f"; break; }
-done
-[ -z $BFBS2JSON ] && err "required bfbs2json is unreachable"
-[ -z $(which jq) ] && err "required jq is not installed"
-[ -z $(which mustach) ] && err "required mostach is not installed"
-[ -z $(which flatcc) ] && err "required flatcc is not installed"
+find_in_libexec() {
+	local name="$1" d f
+	for d in "$PGDIR" "$PGDIR/../libexec" "$PGDIR/libexec"; do
+		f="$d/$name"
+		[ -x "$f" ] && { echo -n "$f"; break; }
+	done
+}
+BFBS2JSON="$(find_in_libexec bfbs2json)"
+JFBSEXTR="$(find_in_libexec jfbsextr)"
+[ -z "$BFBS2JSON" ] && err "required bfbs2json is unreachable"
+[ -z "$JFBSEXTR" ] && err "required jfbsextr is unreachable"
+[ -z "$(which mustach)" ] && err "required mustach is not installed"
+[ -z "$(which flatcc)" ] && err "required flatcc is not installed"
 
-###########################
-# Generate intermid files #
-###########################
+###############################
+# Generate intermediate files #
+###############################
 
 # binary flatbuffer schema
 BFBS="$TEMPDIR/$fbsname.bfbs"
@@ -219,21 +227,9 @@ flatcc --schema -o "$TEMPDIR" "$fbschema"
 [ -e "$BFBS" ] || err "fail to generate binary flatbuffer schema $BFBS"
 
 # Json description of schema
-JSON_SCHEMA="$TEMPDIR/$fbsname.json"
-$BFBS2JSON "$BFBS" | jq . > "$JSON_SCHEMA"
-[ -e "$JSON_SCHEMA" ] || err "Fail to generate json description of schema $JSON_SCHEMA"
-
-# Json description of rpc types
-JQTYPES="[.services[].calls[]|.request,.response]|unique|{\"project_name\": \"$prjname\", types:[.[]|{typename:.name,params:[{paramname:.fields[].name}]}]}"
-RPC_TYPES="$TEMPDIR/$outname-rpc-types.json"
-jq "$JQTYPES" < "$JSON_SCHEMA" > "$RPC_TYPES"
-[ -s "$RPC_TYPES" ] || err "Fail to generate json description of rpc types $RPC_TYPES"
-
-# Json description of rpc apis
-JQAPIS="{\"project_name\":\"$prjname\",apis:[.services[]|{apiname:.name,verbs:[.calls[]|{verbname:.name,request:.request.name,response:.response.name}]}]}"
-RPC_APIS="$TEMPDIR/$outname-rpc-apis.json"
-jq "$JQAPIS" < "$JSON_SCHEMA" > "$RPC_APIS"
-[ -s "$RPC_APIS" ] || err "Fail to generate json description of rpc apis $RPC_APIS"
+RPC_JSON="$TEMPDIR/$fbsname.json"
+$BFBS2JSON "$BFBS" | $JFBSEXTR --pretty --name "$prjname" > "$RPC_JSON"
+[ -e "$RPC_JSON" ] || err "Fail to generate json extract of schema $RPC_JSON"
 
 ###################
 # generate output #
@@ -251,26 +247,26 @@ flatcc -c -a --json --outfile="$out_prefix-flatcc.h" "$fbschema"
 # converter
 if [[ -n "${param[converter]}" ]]; then
 	echo "generating : $out_prefix-fbcvt.c"
-	fbgen cvt "$out_prefix-fbcvt.c" "$RPC_TYPES"
+	fbgen cvt "$out_prefix-fbcvt.c" "$RPC_JSON"
 	echo "generating : $out_prefix-fbcvt.h"
-	fbgen cvt "$out_prefix-fbcvt.h" "$RPC_TYPES"
+	fbgen cvt "$out_prefix-fbcvt.h" "$RPC_JSON"
 fi
 
 # api
 if [[ -n "${param[api]}" ]]; then
 	echo "generating : $out_prefix-fbapi.c"
-	fbgen api "$out_prefix-fbapi.c" "$RPC_APIS"
+	fbgen api "$out_prefix-fbapi.c" "$RPC_JSON"
 fi
 
 # client
 if [[ -n "${param[client]}" ]]; then
 	echo "generating : $out_prefix-fbcli.c"
-	fbgen cli "$out_prefix-fbcli.c" "$RPC_APIS"
+	fbgen cli "$out_prefix-fbcli.c" "$RPC_JSON"
 fi
 
 # cmake
 if [[ -n "${param[cmake]}" ]]; then
 	echo "generating : $(dirname "$out_prefix")/CMakeLists.txt"
 	template=$(find_template fb-template-CMakeLists.txt)
-	mustach $RPC_APIS $template > "$(dirname "$out_prefix")/CMakeLists.txt"
+	mustach $RPC_JSON $template > "$(dirname "$out_prefix")/CMakeLists.txt"
 fi
