Improve afb-fbgen script

diff --git a/flatbuffers/afb-fbgen b/flatbuffers/afb-fbgen
--- a/flatbuffers/afb-fbgen
+++ b/flatbuffers/afb-fbgen
@@ -5,29 +5,34 @@
 # jq remplacé par un binaire ?
 
 # template will be stored in :
-# prefix/afb-idl/afb-flatbuffers/tamplates
+# prefix/afb-idl/afb-flatbuffers/templates
 
 # sous execs
 # prefix/libexec/afbidl
 
-PROGRAMME=$0
-PGNAME=${PROGRAMME##*/}
-PGNAME=${PGNAME%.*}
-TEMP_PATH="/tmp/$PGNAME"
-TEMPLATE_PATH="$(pwd)"
-SUBEXEC_PATH="$(pwd)/libexec"
+
+corename() {
+	local n="$(basename "$1")"
+	echo -n "${n%.*}"
+}
+
+PROGRAM=$0
+PGNAME=$(corename $0)
+PGDIR=$(dirname $0)
+TEMPDIR="/tmp/$PGNAME.$$"
+: ${TEMPLATE_PATH:=$PWD}
 
 usage() {
 	echo "Usage :"
 	echo " "
-	echo "  $PROGRAMME FLATBUFFERS_SCHEMA [OPTION...]"
-	echo "  $PROGRAMME -h | --help"
+	echo "  $PROGRAM FLATBUFFERS_SCHEMA [OPTION...]"
+	echo "  $PROGRAM -h | --help"
 	echo " "
 	echo "Options :"
 	echo " "
 	echo "  -c | --converter            generate a converter"
-	echo "  -a | --api                  generate an api scelet"
-	echo "  -l | --client               generate an client scelet"
+	echo "  -a | --api                  generate an api skeleton"
+	echo "  -l | --client               generate an client skeleton"
 	echo "  -m | --cmake                generate the CMakeLists.txt"
 	echo "  -h | --help                 display help"
 	echo "  -o | --out-prefix PREFIX    specify output prefix. By default output"
@@ -42,18 +47,38 @@ err() {
 	exit 1
 }
 
+declare -a TPATH
+while [ -n "$TEMPLATE_PATH" ]; do
+	p="${TEMPLATE_PATH%%:*}"
+	TPATH+=("$p")
+	[ "$p" =  "$TEMPLATE_PATH" ] && break;
+	TEMPLATE_PATH="${TEMPLATE_PATH#*:}"
+done
+SUBPATH="afb-idl/afb-flatbuffers"
+TPATH+=("$PWD" "$HOME/.config/$SUBPATH" "$PGDIR/../share/$SUBPATH" "$PGDIR")
+find_template() {
+	for d in "${TPATH[@]}"; do
+		f="$d/$1"
+		[ -f "$f" ] && { echo "$f"; return 0; }
+	done
+	return 1
+}
+
 header() {
 	echo "/*"
-	echo " * generated by ${1} based on ${2} as schema and ${3} as tamplate"
+	echo " * generated by $1 based on $2 as schema and $3 as template"
 	echo " */"
 	echo " "
 }
 
-find_template() {
-	for d in "$PWD" "$HOME/.config/afb-idl/afb-flatbuffers" "$(dirname "$PROGRAMME")/../share/afb-idl/afb-flatbuffers" "$(dirname "$0")" "${TAMPLATE_PATH}"; do
-		f="${d}/${1}"
-		[ -f "${f}" ] && { echo ${f}; break; }
-	done
+generate() {
+	# generate header
+	header "$PGNAME" "$1" "$2"
+
+	# Finaly generate the c code with mustach
+	# baised on the json input file and the template
+	# and put it into output file
+	mustach "$1" "$2"
 }
 
 fbgen() {
@@ -62,7 +87,7 @@ fbgen() {
 		cvt) ext=cvt; ixt=types;; # generate a convreter
 		cli) ext=cli; ixt=apis;;  # generate a client
 		api) ext=api; ixt=apis;;  # generate an api
-		*) err "invalid call"     # otherwaiy return an error
+		*) err "invalid call"     # otherwise return an error
 	esac
 	
 	# Parse the output file name <ofile>-fb${ext}.<wg>
@@ -70,8 +95,8 @@ fbgen() {
 	# $ofile = "sample"
 	# $wg = "c"
 	# NB: by default <wg> is "c"
-	[ -z "${2}" ] && err "no arg"
-	ofile="${2}"
+	[ -z "$2" ] && err "no arg"
+	ofile="$2"
 	wg="${ofile##*.}"
 	wg="${wg:-c}"
 	ofile="${ofile%.*}"
@@ -82,27 +107,20 @@ fbgen() {
 	inspec="${3:-${ofile}-rpc-types.json}"
 
 	# Return error if not found
-	[ -f "${inspec}" ] || err "spec ${inspec} not found"
+	[ -f "$inspec" ] || err "spec $inspec not found"
 
-
-	# search for a tamplate named fd-tamplate-<ext>.<wg> in working directory
+	# search for a template named fd-template-<ext>.<wg> in working directory
 	# then in afb-ild config directory and finaly in <executable dir>/../share/afbidl
-	templ=$(find_template "fb-template-${ext}.${wg}")
+	if ! templ=$(find_template "fb-template-$ext.$wg"); then
+		# return error if no template is found
+		err "template fb-template-$ext.$wg not found"
+	fi
 
-	# return error if no tamplate is found
-	[ -z "${templ}" ] && err "template fb-template-${ext}.${wg} not found"
-
-	# generate header
-	echo "$(header ${0##*/} $inspec ${templ##*/})" > "${ofile}-fb${ext}.${wg}"
-
-	# Finaly generate the c code with mustach
-	# baised on the json input file and the template
-	# and put it into output file
-	mustach "${inspec}" "${templ}" >> "${ofile}-fb${ext}.${wg}"
+	# generate the file
+	generate "$inspec" "$templ" > "$ofile-fb$ext.$wg"
 }
 
 POSITIONAL=()
-
 declare -A param
 
 while [[ $# -gt 0 ]]; do
@@ -127,8 +145,7 @@ while [[ $# -gt 0 ]]; do
 
 		-o|--out-prefix)
 		out_prefix=$2
-		shift # past argument
-		shift # past argument
+		shift 2 # past argument
 		;;
 
 		-m|--cmake)
@@ -147,10 +164,8 @@ while [[ $# -gt 0 ]]; do
 	esac
 done
 
-set -- "${POSITIONAL[@]}" # restore positional parameters
-
-# If nothing is specifyed build all
-if [[ -z ${param[@]} ]]; then
+# If nothing is specified build all
+if [[ ${#param[@]} -eq 0 ]]; then
 	param[converter]=YES
 	param[api]=YES
 	param[client]=YES
@@ -158,33 +173,36 @@ if [[ -z ${param[@]} ]]; then
 fi
 
 # Get flatbuffer schema as imput
-if [[ -z "${1}" ]]; then
+if [[ ${#POSITIONAL[@]} -eq 0 ]]; then
 	echo "Flatbuffers schema is missing !"
 	usage
 fi
-fbschema="${1}"
+
+set -- "${POSITIONAL[@]}" # restore positional parameters
+fbschema="$1"
+fbsname="$(corename $fbschema)"
+prjname="$fbsname"
 
 # Set output prefix based on input if not specifyed with option --output-prefix
-if [[ -z ${out_prefix} ]]; then 
-	out_prefix=${fbschema%.*}
-	out_prefix=${out_prefix##*/}
+if [[ -z "$out_prefix" ]]; then 
+	out_prefix="$fbsname"
 
 # if output prefix is a directory add input name as file prefix
-elif [[ ! -z ${out_prefix%/*} && -z ${out_prefix##*/} ]]; then
-	out_prefix_path=${out_prefix%/*}
-	out_prefix=${fbschema%.*}
-	out_prefix=${out_prefix_path}/${out_prefix##*/}
+elif [[ "${out_prefix%/}" != "$out_prefix" ]]; then
+	out_prefix+="$fbsname"
 fi
+outname="$(corename "$out_prefix")"
 
 echo "selected params : ${!param[@]}"
-echo "fb schema       : ${fbschema}"
-echo "out prefix      : ${out_prefix}"
+echo "fb schema       : $fbschema"
+echo "out prefix      : $out_prefix"
 
 # check dependencies
-[ ! -e $TEMP_PATH ] && mkdir -p $TEMP_PATH
-for d in "$(dirname "$0")" "$(dirname "$0")/../libexec" "$(dirname "$0")/libexec"; do
+trap "rm -r '$TEMPDIR'" EXIT
+[ ! -e "$TEMPDIR" ] && mkdir -p "$TEMPDIR"
+for d in "$PGDIR" "$PGDIR/../libexec" "$PGDIR/libexec"; do
 	f="$d/bfbs2json"
-	[ -x "${f}" ] && { BFBS2JSON="${f}"; break; }
+	[ -x "$f" ] && { BFBS2JSON="$f"; break; }
 done
 [ -z $BFBS2JSON ] && err "required bfbs2json is unreachable"
 [ -z $(which jq) ] && err "required jq is not installed"
@@ -196,65 +214,63 @@ done
 ###########################
 
 # binary flatbuffer schema
-flatcc --schema -o $TEMP_PATH $fbschema
-BFBS=${fbschema%.*}.bfbs
-BFBS=$TEMP_PATH/${BFBS##*/}
-[ ! -e $BFBS ] && err "fail to generate binary flatbuffer schema $BFBS"
+BFBS="$TEMPDIR/$fbsname.bfbs"
+flatcc --schema -o "$TEMPDIR" "$fbschema"
+[ -e "$BFBS" ] || err "fail to generate binary flatbuffer schema $BFBS"
 
 # Json description of schema
-JSON_SCHEMA=$TEMP_PATH/${out_prefix##*/}.json
-$BFBS2JSON $BFBS | jq . > $JSON_SCHEMA
-[ ! -e $JSON_SCHEMA ] && err "Fail to generate json description of schema $JSON_SCHEMA"
+JSON_SCHEMA="$TEMPDIR/$fbsname.json"
+$BFBS2JSON "$BFBS" | jq . > "$JSON_SCHEMA"
+[ -e "$JSON_SCHEMA" ] || err "Fail to generate json description of schema $JSON_SCHEMA"
 
 # Json description of rpc types
-JQTYPES='[.services[].calls[]|.request,.response]|unique|{"project_name": "'${out_prefix##*/}'", types:[.[]|{typename:.name,params:[{paramname:.fields[].name}]}]}'
-RPC_TYPES=$TEMP_PATH/${out_prefix##*/}-rpc-types.json
-jq "$JQTYPES" < $JSON_SCHEMA > $RPC_TYPES
-[ ! -e $RPC_TYPES ] || [  ! -s $RPC_TYPES ] && err "Fail to generate json description of rpc types $RPC_TYPES"
+JQTYPES="[.services[].calls[]|.request,.response]|unique|{\"project_name\": \"$prjname\", types:[.[]|{typename:.name,params:[{paramname:.fields[].name}]}]}"
+RPC_TYPES="$TEMPDIR/$outname-rpc-types.json"
+jq "$JQTYPES" < "$JSON_SCHEMA" > "$RPC_TYPES"
+[ -s "$RPC_TYPES" ] || err "Fail to generate json description of rpc types $RPC_TYPES"
 
 # Json description of rpc apis
-JQAPIS='{"project_name":"'${out_prefix##*/}'",apis:[.services[]|{apiname:.name,verbs:[.calls[]|{verbname:.name,request:.request.name,response:.response.name}]}]}'
-RPC_APIS=$TEMP_PATH/${out_prefix##*/}-rpc-apis.json
-jq "$JQAPIS" < $JSON_SCHEMA > $RPC_APIS
-[ ! -e $RPC_APIS ] || [ ! -s $RPC_APIS ] && err "Fail to generate json description of rpc apis $RPC_APIS"
+JQAPIS="{\"project_name\":\"$prjname\",apis:[.services[]|{apiname:.name,verbs:[.calls[]|{verbname:.name,request:.request.name,response:.response.name}]}]}"
+RPC_APIS="$TEMPDIR/$outname-rpc-apis.json"
+jq "$JQAPIS" < "$JSON_SCHEMA" > "$RPC_APIS"
+[ -s "$RPC_APIS" ] || err "Fail to generate json description of rpc apis $RPC_APIS"
 
 ###################
 # generate output #
 ###################
 
 # if out directory doesn't exist create it
-[ "${out_prefix%/*}" != "$out_prefix" ] && [ ! -e "${out_prefix%/*}" ] && mkdir -p ${out_prefix%/*}
+if [ "${out_prefix%/*}" != "$out_prefix" ]; then
+	mkdir -p "${out_prefix%/*}" || err "Failed to create directory ${out_prefix%/*}"
+fi
 
 # flatcc header
-echo "generating : ${out_prefix}_flatcc.h"
-flatcc -c -a --json --outfile="${out_prefix}_flatcc.h" $fbschema
+echo "generating : $out_prefix-flatcc.h"
+flatcc -c -a --json --outfile="$out_prefix-flatcc.h" "$fbschema"
 
 # converter
 if [[ -n "${param[converter]}" ]]; then
 	echo "generating : $out_prefix-fbcvt.c"
-	fbgen cvt "$out_prefix-fbcvt.c" $RPC_TYPES
+	fbgen cvt "$out_prefix-fbcvt.c" "$RPC_TYPES"
 	echo "generating : $out_prefix-fbcvt.h"
-	fbgen cvt "$out_prefix-fbcvt.h" $RPC_TYPES
+	fbgen cvt "$out_prefix-fbcvt.h" "$RPC_TYPES"
 fi
 
 # api
 if [[ -n "${param[api]}" ]]; then
 	echo "generating : $out_prefix-fbapi.c"
-	fbgen api "$out_prefix-fbapi.c" $RPC_APIS
+	fbgen api "$out_prefix-fbapi.c" "$RPC_APIS"
 fi
 
 # client
 if [[ -n "${param[client]}" ]]; then
 	echo "generating : $out_prefix-fbcli.c"
-	fbgen cli "$out_prefix-fbcli.c" $RPC_APIS
+	fbgen cli "$out_prefix-fbcli.c" "$RPC_APIS"
 fi
 
 # cmake
 if [[ -n "${param[cmake]}" ]]; then
-	echo "generating : $(dirname ${out_prefix})/CMakeLists.txt"
-	tamplate=$(find_template fb-template-CMakeLists.txt)
-	mustach $RPC_APIS $tamplate > "$(dirname ${out_prefix})/CMakeLists.txt"
+	echo "generating : $(dirname "$out_prefix")/CMakeLists.txt"
+	template=$(find_template fb-template-CMakeLists.txt)
+	mustach $RPC_APIS $template > "$(dirname "$out_prefix")/CMakeLists.txt"
 fi
-
-echo "remove intermed files : " $TEMP_PATH/${out_prefix##*/}*
-rm $TEMP_PATH/${out_prefix##*/}*
